package org.gisik.csv;

import org.gisik.EmptyFileException;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Parser for CSV files.
 * <p>
 * Handles CSV files with configurable separators, quoted fields, and optional headers.
 * Provides access to column names and allows extracting numeric data from specific columns.
 */
public class CsvParser {

    /**
     * Internal class representing a column name.
     * Keeps track of whether the name comes from the file header or is autogenerated.
     */
    static class NameInfo {
        String text;
        boolean realName;

        /**
         * Constructs a NameInfo object.
         *
         * @param text the column name text
         * @param headerSize index used to generate default name if text is empty
         */
        NameInfo(String text, int headerSize) {
            if(text.isEmpty()) {
                realName = false;
                this.text = String.format("column %d", headerSize+1);
            } else {
                this.text = text;
                realName = true;
            }
        }

        @Override
        public String toString() {
            return text;
        }
    }

    private final List<String> lines;
    private List<NameInfo> header;
    private char separator;

    /**
     * Constructs a CSV parser for the specified file.
     *
     * @param file the CSV file to parse
     * @param separator the separator character (e.g., ',' or ';')
     * @throws IOException if the file cannot be read
     * @throws EmptyFileException if the file is empty
     */
    CsvParser(File file, char separator) throws IOException {
        lines = Files.readAllLines(file.toPath());
        if(lines.isEmpty()) {
            throw new EmptyFileException("Empty file");
        }
        setSeparator(separator); //TODO: check if separator length is 1
        System.out.println(header);
    }

    /**
     * Returns the column names.
     *
     * @return an array of column names
     */
    public String[] getColumnNames() {
        String[] ret = new String[header.size()];
        for(int i = 0; i < header.size(); i++) {
            ret[i] = header.get(i).text;
        }
        return ret;
    }

    /**
     * Returns the current CSV separator.
     *
     * @return the separator character
     */
    public char getSeparator() {
        return separator;
    }

    /**
    * Sets the CSV separator and re-reads the header row.
    *
    * @param separator the new separator character
     */
    public void setSeparator(char separator) {
        this.separator = separator;
        readHeader();
    }

    /**
     * Reads the header row of the CSV file and populates column names.
     * Handles quoted fields and adds default names for empty columns.
     */
    private void readHeader() {
        header = new ArrayList<>();
        int columnsNum = countColumns();
        String row = lines.get(0);
        boolean opened = false;
        String name = "";
        for(int i = 0; i < row.length(); i++) {
            char cur = row.charAt(i);
            if (cur != '"') {
                if(cur == separator && !opened) {
                    header.add(new NameInfo(name, header.size()));
                    name = "";
                } else {
                    name += cur;
                }
            } else {
                opened ^= true;
            }
        }
        header.add(new NameInfo(name, header.size()));

        int headerSize = header.size();
        if(headerSize < columnsNum) {
            for(int i=0; i<columnsNum-headerSize;i++) {
                header.add(new NameInfo("", header.size()));
            }
        }
    }

    /**
     * Counts the maximum number of columns in any row of the CSV file.
     *
     * @return the maximum column count
     */
    private int countColumns() {
        int max = 1;
        boolean opened = false;
        for(String line : lines) {
            int columnCount = 1;
            for (int i = 0; i < line.length(); i++) {
                if (line.charAt(i) == '"') {
                    opened ^= true;
                }
                if (line.charAt(i) == separator && !opened) {
                    columnCount++;
                }
            }
            max = Math.max(max, columnCount);
        }
        return max;
    }

    /**
     * Converts a column name to its zero-based index.
     *
     * @param colName the column name
     * @return the column index, or -1 if not found
     */
    private int nameToColumnIndex(String colName) {
        int idx = 0;
        for(NameInfo h : header) {
            if (h.text.equals(colName)) {
                return idx;
            }
            idx++;
        }
        return -1; // shoudnt happen;
    }

    /**
     * Parses numeric values from the specified column.
     *
     * @param colName the column name
     * @param firstRow whether the first row contains data or headers
     * @return a list of Double values (null for invalid entries)
     */
    public List<Double> parseColumnByName(String colName, boolean firstRow) {
        List<Double> ret = new ArrayList<>();
        int idx = nameToColumnIndex(colName);
        boolean opened = false;
        boolean isFirst = true;
        for(String line : lines) {
            if(isFirst && !firstRow) {
                isFirst = false;
                continue;
            }
            String name = "";
            int curIdx = 0;
            for (int i = 0; i < line.length(); i++) {
                char cur = line.charAt(i);
                if (cur != '"') {
                    if (cur != separator) {
                        if(curIdx == idx) {
                            name +=  line.charAt(i);
                        }
                    } else if(!opened) {
                        if(curIdx == idx) {
                            try {
                                ret.add(Double.parseDouble(name.trim()));
                            } catch(NumberFormatException e) {
                                ret.add(null);
                            }
                            break;
                        }
                        curIdx++;
                    }
                } else {
                    opened ^= true;
                }
            }
            if(name.isEmpty()) {
                ret.add(null);
            }
        }
        return ret;
    }

    /**
     * Returns the raw content of the CSV file as a string.
     *
     * @return the full CSV content
     */
    public String getFileContent() {
        String ret = "";
        for (String line : lines) {
            ret += line + "\n";
        }
        return ret;
    }

    /**
     * Converts a combo box text description of a separator to a character.
     *
     * @param txt the text from the combo box ("TAB", "SPACE", or a single character)
     * @return the corresponding separator character
     */
    static public char comboTextToChar(String txt) {
        if (Objects.equals(txt, "TAB")) {
            return '\t';
        } else if (Objects.equals(txt, "SPACE")) {
            return ' ';
        }
        return txt.charAt(0);
    }
}
